## Non Graded Challenge 4

In [1]:
import numpy as np

1. Membuat tensor

In [2]:
a = np.array([[23, 50], [7, 12]])

b = np.array([[57, 57], [99, 43]])

c = np.array([[75, 21], [57, 12]])

d = np.array([[87, 26], [18, 84]])

print(a, b, c, d)

[[23 50]
 [ 7 12]] [[57 57]
 [99 43]] [[75 21]
 [57 12]] [[87 26]
 [18 84]]


In [7]:
tensor = np.array([a, b, c, d])
tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 57],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

2. Melakukan perkalian matrix

In [9]:
A = np.array([[23, 50, 19], [7, 12, 109], [57, 67, 98]])

B = np.array([[17], [22], [19]])

In [10]:
A @ B

array([[1852],
       [2454],
       [4305]])

3. Melakukan Transpose, menghitung determinan, dan inverse terhadap matrix

In [12]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [17]:
Transpose = A.T
Transpose

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [23]:
Determinan = np.linalg.det(A)
Determinan

131344.0000000002

In [18]:
Inverse = np.linalg.inv(A)
Inverse

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])