## Non Graded Challenge 5

Apakah ([[1, 3]]) adalah eigenvector dari ([[1 -1], [6, 4]])

In [3]:
import numpy as np

In [4]:
A = np.array([[1, -1],
[6,4]])

A

array([[ 1, -1],
       [ 6,  4]])

In [5]:
eig_val, eig_vec = np.linalg.eig(A)

In [9]:
eig_vec.real

array([[-0.23145502, -0.23145502],
       [ 0.9258201 ,  0.9258201 ]])

In [8]:
deconstruct = eig_vec @ np.diag(eig_val) @ np.linalg.inv(eig_vec)
deconstruct.real

array([[ 1., -1.],
       [ 6.,  4.]])