## Non Graded Challenge 5

Apakah ([[1, 3]]) adalah eigenvector dari ([[1 -1], [6, 4]])

In [2]:
import numpy as np

In [5]:
A = np.array([[1, -1],
[6,4]])

A

array([[ 1, -1],
       [ 6,  4]])

In [7]:
eig_val, eig_vec = np.linalg.eig(A)

In [8]:
eig_vec

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])

In [9]:
deconstruct = eig_vec @ np.diag(eig_val) @ np.linalg.inv(eig_vec)
deconstruct

array([[ 1.-4.70796047e-17j, -1.-3.25661782e-18j],
       [ 6.+3.20635860e-16j,  4.-7.82938924e-17j]])

Bentuknya mirip akan tetapi bukan bilangan real?? - coba tanya Ka Rafif atau nonton videonya lagi