# MATRIX

In [1]:
import numpy as np

In [3]:
A =np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
A.shape # dimensi 3 baris & 2 kolom

(3, 2)

In [6]:
A = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

In [7]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
A[1]

array([4, 5, 6])

In [9]:
A[1][2]

6

In [10]:
A[1,2]

6

In [11]:
A[:, 2]

array([3, 6, 9])

In [12]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.diag(np.diag(A))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [15]:
np.eye(3) # matrix identitas 3 x 3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.zeros([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Operasi Aritmatika
- penjumlahan
- pengurangan
- pembagiana
- perkalian

In [19]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
B = np.array([[1, 2, 8],
            [4, 5, 6],
            [2, 5, 0]])
B

array([[1, 2, 8],
       [4, 5, 6],
       [2, 5, 0]])

**Penjumlahan**

In [24]:
A + B # terhadap matriks

array([[ 2,  4, 11],
       [ 8, 10, 12],
       [ 9, 13,  9]])

In [25]:
10 + A # skalar

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

**Pengurangan**

In [26]:
A - B

array([[ 0,  0, -5],
       [ 0,  0,  0],
       [ 5,  3,  9]])

In [27]:
10 - A

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

**Pembagian**

In [28]:
B / A

array([[1.        , 1.        , 2.66666667],
       [1.        , 1.        , 1.        ],
       [0.28571429, 0.625     , 0.        ]])

**perkalian**

In [29]:
A * 10 # perkalian dengan skalar

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
#perkalian hadamard product (element - wise multiplication)
A * np.eye(3) 

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

1. aturan perkalian matrix: C(m, n) = A(m, k) . B(k, n)
> kolom matrix A = baris matrix B
2. perkalian di dalam matriks menggunakan "@" seperti dot product di scalar 



In [43]:
A @ B

array([[ 15,  27,  20],
       [ 36,  63,  62],
       [ 57,  99, 104]])

In [39]:
J = np.array([[1,2,0],
[0,3,1],
[1, 0, 0]])

J

array([[1, 2, 0],
       [0, 3, 1],
       [1, 0, 0]])

In [38]:
K = np.array([[0, 1],
[1, 2],
[0, 1]])

K

array([[0, 1],
       [1, 2],
       [0, 1]])

In [42]:
J @ K

array([[2, 5],
       [3, 7],
       [0, 1]])

**Transpose**

In [45]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Inverse**

In [53]:
B

array([[1, 2, 8],
       [4, 5, 6],
       [2, 5, 0]])

In [55]:
inv_B = np.linalg.inv(B)
inv_B

array([[-0.40540541,  0.54054054, -0.37837838],
       [ 0.16216216, -0.21621622,  0.35135135],
       [ 0.13513514, -0.01351351, -0.04054054]])

In [56]:
B @ inv_B

array([[ 1.00000000e+00,  0.00000000e+00,  5.55111512e-17],
       [-5.55111512e-17,  1.00000000e+00, -1.38777878e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [58]:
np.linalg.inv(A)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [59]:
np.linalg.det(A)

-9.51619735392994e-16

In [ ]:
# Singular matrix : det = 0

In [70]:
c = np.array([[1, 2],
[3, 6]])

det_c= round(np.linalg.det(c)) #bilangannya 0
det_c

0

In [68]:
np.linalg.inv(det_c) # det 0 jadi matrix singular

LinAlgError: 0-dimensional array given. Array must be at least two-dimensional

- det(A) = a.d - b.c

**Tensor**

- 0 - D array = scalar
- 1 - D array = vector
- 2 - D array = matrix
- n - D array = Tensor (Multi dimensional array/ matrix yang dibungkus dalam list)

In [75]:
x = np.array([[1, 5, 1, 3],
[3, 7, 1, 1]])

y = np.array([[5, 1, 2, 5],
[5, 1, 0, 0]])

z = np.array([[0, 6, 1, 0],
[3, 1, 0, 0]])

In [77]:
x.shape #pastiin shapenya sama untuk tensor

(2, 4)

In [78]:
tensor = np.array([x, y, z])
tensor

array([[[1, 5, 1, 3],
        [3, 7, 1, 1]],

       [[5, 1, 2, 5],
        [5, 1, 0, 0]],

       [[0, 6, 1, 0],
        [3, 1, 0, 0]]])

In [80]:
tensor.shape # 3 matrix, 2, baris, 4 kolom

(3, 2, 4)