# **VECTOR**

In [1]:
import numpy as np

In [3]:
np.array([1,2,3]) 
#convert ke array agar bisa dioperasikan secara matematika 

array([1, 2, 3])

In [21]:
list_1 = [1, 2, 3]
list_2 = [4, 5, 6]

list_1 + list_2
# hasilnya malah seperti di append

[1, 2, 3, 4, 5, 6]

In [22]:
arr_1 = np.array(list_1)
arr_2 = np.array(list_2)

arr_1 + arr_2

array([5, 7, 9])

**INDEXING**

In [23]:
arr_1

array([1, 2, 3])

In [24]:
arr_1[1]

2

In [25]:
arr_1.size

3

## vector norm
np.linalg.norm(v)

In [26]:
vec_1 = np.array([6,8])

np.linalg.norm(vec_1) # magnitude vector L2/ eucldeand distance sqrt(sigma u^2)

10.0

L2 / eucldeand distance sqrt(sigma u^2)

L1 / manhattan distance

## Operasi Aritmatika

Penjumlahan

In [27]:
print(arr_1, arr_2)

[1 2 3] [4 5 6]


In [28]:
# penjumlahan vector dengan scalar/ bilangan
arr_1 + 10

array([11, 12, 13])

In [29]:
#penjumlahan vector dengan vector
arr_1 + arr_2

array([5, 7, 9])

In [ ]:
arr_3 = np.array([2, 5, 6, 1, 3])

arr_1 + arr_3 # akan muncul error karena jumlah elemen tidak sama 

Pengurangan

In [30]:
# pengurangan vector dengan scalar/ bilangan
arr_1 - 10

array([-9, -8, -7])

In [31]:
10 - arr_1

array([9, 8, 7])

In [32]:
# pengurangan vector dengan vector
arr_1 - arr_2

array([-3, -3, -3])

Pembagian

In [33]:
print(arr_1, arr_2)

[1 2 3] [4 5 6]


In [35]:
# pembagian vector terhadap scalar/bilangan
arr_1 / 2

array([0.5, 1. , 1.5])

In [36]:
# pembagian vector terhadap vector
arr_2 / arr_1

array([4. , 2.5, 2. ])

Perkalian
- dengan scalar/bilangan
- dengan vector (element-wise multiplication)
- dot product

In [39]:
print(arr_1, arr_2)

[1 2 3] [4 5 6]


In [37]:
# perkalian vector dengan scalar / bilangan
arr_1 * 10

array([10, 20, 30])

In [38]:
# perkalian vector dengan vector
arr_1 * arr_2

array([ 4, 10, 18])

In [43]:
# dot product (hasil = scalar)
arr_1 @ arr_2

32

In [44]:
np.dot(arr_1, arr_2)

32

In [45]:
arr_1.dot(arr_2)

32

In [46]:
# mencari dot product dapat digunakan untuk mencari angle
# angle = merepresentasikan kedekatan antara kedua vector
# a . b = ||a|| ||b|| cos 0
# cosine similarity

Cosince Similarity
- mencari dot product dapat digunakan untuk mencari angle
- angle = merepresentasikan kedekatan antara kedua vector
- a . b = ||a|| ||b|| cos 0

In [49]:
cos_theta = arr_1 @ arr_2 / (np.linalg.norm(arr_1) * np.linalg.norm(arr_2))
cos_theta # 0.97 atau 97 % yang beratai dekat 

0.9746318461970762

In [52]:
v_1 = np.array([5, 0])
v_2 = np.array([8, 0])

cos_theta = v_1 @ v_2 / (np.linalg.norm(v_1) * np.linalg.norm(v_2))
cos_theta # sangat dekat karena 100 %

1.0

Implementasi cosine similarity

- kalimat 1 = saya pergi ke rumah nenek saya
- kalimat 2 = saya pergi ke rumah kakek saya

kata unique (saya, pergi, ke , rumah, nenek, kakek)

In [54]:
kal_1 = [2, 1, 1, 1, 1, 0]
kal_2 = [2, 1, 1, 1, 0, 1]

kal_1 = np.array(kal_1)
kal_2 = np.array(kal_2)

print(kal_1, kal_2)

[2 1 1 1 1 0] [2 1 1 1 0 1]


In [56]:
cos_theta = kal_1 @ kal_2 / (np.linalg.norm(kal_1) * np.linalg.norm(kal_2))
cos_theta

0.8749999999999998

- kalimat 1 = kemarin saya pergi ke surabaya
- kalimat 2 = ibu saya sedang berbelanja

kata unique ( kemarin, saya, pergi, ke , surabaya, ibu, sedang, berbelanja)

In [57]:
vec_1 = [1, 1, 1, 1, 1, 0, 0, 0]
vec_2 = [0, 1, 0, 0, 0, 1, 1, 1]

vec_1 = np.array(vec_1)
vec_2 = np.array(vec_2)

print(vec_1, vec_2)

[1 1 1 1 1 0 0 0] [0 1 0 0 0 1 1 1]


In [58]:
cos_theta = vec_1 @ vec_2 / (np.linalg.norm(vec_1) * np.linalg.norm(vec_2))
cos_theta

0.22360679774997896