## NUMPY

In [1]:
import numpy as np

In [3]:
tinggi = [1.7, 1.8, 1.9, 1.10, 1.11, 1.12]
berat = [60.5, 61.5, 62.5, 63.5, 64.5, 65.6]

#operator pembagian
np_tinggi=np.array(tinggi)
np_berat = np.array(berat)

np_berat/np_tinggi

array([35.58823529, 34.16666667, 32.89473684, 57.72727273, 58.10810811,
       58.57142857])

In [5]:
np.arange(5) #hasil akan berdasarkan index (0,1,2,3,4)

array([0, 1, 2, 3, 4])

In [11]:
print(np.arange(3,9,2))

[3 5 7]


In [8]:
arr= np.array([1,2,3,4])
arr_new=np.append(arr,[7,8,9])

In [9]:
arr_new

array([1, 2, 3, 4, 7, 8, 9])

In [10]:
np.delete(arr_new,3)

array([1, 2, 3, 7, 8, 9])

# 0-D/ skalar

In [13]:
arr= np.array(6)
print(arr)

6


In [14]:
arr.ndim #mengetahui jumlah dimensi 

0

In [15]:
arr.shape

()

# 1-D/ vektor 

In [16]:
arr= np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [17]:
arr.ndim

1

In [18]:
arr.shape

(4,)

# 2-D/ matriks

In [24]:
arr=np.array([[1, 2, 3, 4],
            [3, 4, 5, 7]])
print(arr)

[[1 2 3 4]
 [3 4 5 7]]


In [25]:
arr.ndim

2

In [26]:
arr.shape

(2, 4)

In [27]:
arr.size

8

In [34]:
arr= np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [35]:
matriks = arr.reshape(3,2)
print(matriks)

[[0 1]
 [2 3]
 [4 5]]


In [36]:
matriks2=arr.reshape(6,1)
print(matriks2)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [37]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [38]:
a.shape

(6,)

In [39]:
a2=a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [40]:
a3=a[:,np.newaxis]
print(a3.shape)
print(a3)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [41]:
arr=np.array([1,2,7,4,10,5])
print(arr[2:6])

[ 7  4 10  5]


In [42]:
arr=np.array([1,2,7,4,10,5,13,11])
print(arr[2:8:3])

[7 5]


In [59]:
arr=np.array([1,2,7,4,10,5,13,11])
print(arr[:8:3])

[ 1  4 13]


In [62]:
arr=np.array([[1,2,3,4,8,10],[5,6,7,8,7,10],[9,10,11,12,11,12]])
print(arr[arr>=3])

[ 3  4  8 10  5  6  7  8  7 10  9 10 11 12 11 12]


In [46]:
arr.ndim

2

In [47]:
arr.shape

(3, 4)

In [63]:
a_1=np.array([[1,1],[2,2]])
a_2=np.array([[3,3],[4,4]])
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [64]:
np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [65]:
arr_new=np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]])
new_arr = arr_new.reshape(2, 3, -1) #unkdown dimension
print(new_arr.shape)
print(new_arr)

(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [66]:
def tambah(var1, var2):
    hasil = var1 + var2
    return hasil

tambah(var1 = 2, var2 = 4)

6

In [67]:
tambah(3,1)

4

In [68]:
hasil_function = tambah(3,1)
hasil_function + 1

5

In [73]:
def tambah_print(var1, var2):
    hasil = var1 + var2
    print(hasil)
tambah_print(var1 = 2, var2 = 4)

6


In [74]:
tambah_print(3,1)

4


In [76]:
hasil_function_print = tambah_print(3,1)
print(tambah_print(3,1))
hasil_function_print + 1 ## beda dengan return

4
4
None


TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [77]:
def tambah(var1, var2):
    hasil = var1 + var2
    return hasil

tambah(var1 = 2, var2 = 4)

6

In [78]:
def dua_kali_jumlah(v_1, v_2):
    result = (v_1 +v_2) * 2
    print (result)

In [79]:
dua_kali_jumlah(1,2)

6


In [80]:
def tambah(var1, var2):
    hasil = var1 + var2
    return hasil
def dua_kali_jumlah(v_1, v_2):
    result = tambah(v_1, v_2) * 2
    print (result)

In [81]:
dua_kali_jumlah(2,5)

14


In [84]:
#Angka yang bisa dengan 7 dan dikali dengan 5, antara 1500 sampe 2700
for i in range(1500, 2701):
    if i % 7 == 0:
        if i % 5 == 0:
            print(i)

1505
1540
1575
1610
1645
1680
1715
1750
1785
1820
1855
1890
1925
1960
1995
2030
2065
2100
2135
2170
2205
2240
2275
2310
2345
2380
2415
2450
2485
2520
2555
2590
2625
2660
2695


In [85]:
#Angka yang bisa dengan 7 dan dikali dengan 5, antara 1500 sampe 2700
for i in range(1500, 2701):
    if (i % 7 == 0) & (i % 5 == 0):
        print(i)

1505
1540
1575
1610
1645
1680
1715
1750
1785
1820
1855
1890
1925
1960
1995
2030
2065
2100
2135
2170
2205
2240
2275
2310
2345
2380
2415
2450
2485
2520
2555
2590
2625
2660
2695


In [99]:
for i in range (1,6):
    print('* '*i)
for y in range(4,0,-1):
    print("* "*y)

* 
* * 
* * * 
* * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


In [87]:
for i in range (4,0,-1): # start di 4, akhir di 0, -1 pengurangan setiap set
    print (i)

4
3
2
1


In [93]:
def search_numb(start, stop, divisible_1):
    for i in range (start, stop+1):
        if (i % divisible_1 == 0) & (i % 5 == 0):
            print(i)

In [94]:
search_numb(start=10, stop=30, divisible_1=2)

10
20
30
