## NUMPY

In [1]:
import numpy as np

In [3]:
tinggi = [1.7, 1.8, 1.9, 1.10, 1.11, 1.12]
berat = [60.5, 61.5, 62.5, 63.5, 64.5, 65.6]

#operator pembagian
np_tinggi=np.array(tinggi)
np_berat = np.array(berat)

np_berat/np_tinggi

array([35.58823529, 34.16666667, 32.89473684, 57.72727273, 58.10810811,
       58.57142857])

In [5]:
np.arange(5) #hasil akan berdasarkan index (0,1,2,3,4)

array([0, 1, 2, 3, 4])

In [11]:
print(np.arange(3,9,2))

[3 5 7]


In [8]:
arr= np.array([1,2,3,4])
arr_new=np.append(arr,[7,8,9])

In [9]:
arr_new

array([1, 2, 3, 4, 7, 8, 9])

In [10]:
np.delete(arr_new,3)

array([1, 2, 3, 7, 8, 9])

# 0-D/ skalar

In [13]:
arr= np.array(6)
print(arr)

6


In [14]:
arr.ndim #mengetahui jumlah dimensi 

0

In [15]:
arr.shape

()

# 1-D/ vektor 

In [16]:
arr= np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [17]:
arr.ndim

1

In [18]:
arr.shape

(4,)

# 2-D/ matriks

In [24]:
arr=np.array([[1, 2, 3, 4],
            [3, 4, 5, 7]])
print(arr)

[[1 2 3 4]
 [3 4 5 7]]


In [25]:
arr.ndim

2

In [26]:
arr.shape

(2, 4)

In [27]:
arr.size

8

In [34]:
arr= np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [35]:
matriks = arr.reshape(3,2)
print(matriks)

[[0 1]
 [2 3]
 [4 5]]


In [36]:
matriks2=arr.reshape(6,1)
print(matriks2)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [37]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [38]:
a.shape

(6,)

In [39]:
a2=a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [40]:
a3=a[:,np.newaxis]
print(a3.shape)
print(a3)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [41]:
arr=np.array([1,2,7,4,10,5])
print(arr[2:6])

[ 7  4 10  5]


In [42]:
arr=np.array([1,2,7,4,10,5,13,11])
print(arr[2:8:3])

[7 5]


In [59]:
arr=np.array([1,2,7,4,10,5,13,11])
print(arr[:8:3])

[ 1  4 13]


In [62]:
arr=np.array([[1,2,3,4,8,10],[5,6,7,8,7,10],[9,10,11,12,11,12]])
print(arr[arr>=3])

[ 3  4  8 10  5  6  7  8  7 10  9 10 11 12 11 12]


In [46]:
arr.ndim

2

In [47]:
arr.shape

(3, 4)

In [63]:
a_1=np.array([[1,1],[2,2]])
a_2=np.array([[3,3],[4,4]])
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [64]:
np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [65]:
arr_new=np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]])
new_arr = arr_new.reshape(2, 3, -1) #unkdown dimension
print(new_arr.shape)
print(new_arr)

(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
